apiVersion: 1

datasources:
  - name: F1_Garage_SQL_Server
    uid: f1-sqlserver
    type: mssql
    access: proxy
    url: $GRAFANA_DB_HOST
    user: $GRAFANA_DB_USER
    secureJsonData:
      password: $GRAFANA_DB_PASSWORD
    jsonData:
      database: $GRAFANA_DB_NAME
      encrypt: 'true'
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: false
    isDefault: true
