{
 "title": "F1 Garage Manager",
 "tags": [
  "academic",
  "f1-garage"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "circuito",
    "label": "circuito",
    "query": "SELECT DISTINCT circuito AS __text, circuito AS __value FROM dbo.v_grafana_carro_historial ORDER BY circuito;"
   },
   {
    "name": "simulation_id",
    "label": "simulation_id",
    "query": "SELECT s.id_simulacion AS __text, s.id_simulacion AS __value FROM dbo.simulacion s JOIN dbo.circuito c ON c.id_circuito = s.id_circuito WHERE c.nombre = ${circuito:sqlstring} ORDER BY s.id_simulacion;"
   },
   {
    "name": "carro",
    "label": "carro",
    "query": "SELECT DISTINCT CONCAT(equipo, ' - ', carro) AS __text, id_carro AS __value FROM dbo.v_grafana_carro_historial ORDER BY __text;"
   }
  ]
 },
 "panels": [
  {
   "title": "Ranking de Resultados",
   "type": "table",
   "description": "Clasificación final de los carros en la simulación seleccionada. Incluye equipo, carro, velocidades, penalizaciones y tiempo final, ordenado por posición.",
   "gridPos": { "x": 0, "y": 13, "h": 18, "w": 24 },
   "targets": [
    {
     "dataset": "f1_garage_tec",
     "rawSql": "SELECT\r\n  posicion,\r\n  equipo,\r\n  carro,\r\n  vrecta,\r\n  vcurva,\r\n  penalizacion,\r\n  tiempo_segundos\r\nFROM dbo.v_grafana_ranking_simulacion\r\nWHERE circuito = ${circuito:sqlstring}\r\n  AND id_simulacion = $simulation_id \r\nORDER BY posicion;\r\n"
    }
   ]
  },
  {
   "title": "Historial del carro (Tiempo por simulación)",
   "type": "timeseries",
   "description": "Este panel muestra la evolución del tiempo del mismo carro a lo largo de distintas simulaciones, permitiendo comparar su desempeño en diferentes condiciones de pista y momentos de simulación.",
   "gridPos": { "x": 12, "y": 0, "h": 13, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "dataset": "f1_garage_tec",
     "rawSql": "SELECT\r\n  fecha_simulacion AS time,\r\n  CAST(tiempo_segundos AS DECIMAL(12,3)) AS value,\r\n  CONCAT('Sim ', CAST(id_simulacion AS VARCHAR(10))) AS sim_label,\r\n  circuito AS circuito_label\r\nFROM dbo.v_grafana_carro_historial\r\nWHERE id_carro = $carro  -- Cambió de carro a id_carro\r\nORDER BY fecha_simulacion;"
    }
   ]
  },
  {
   "title": "Tiempo vs P / A / M del carro (Simulación)",
   "type": "barchart",
   "description": "Este panel relaciona el tiempo final del carro con los valores acumulados de Potencia (P), Aerodinámica (A) y Manejo (M) del setup utilizado en una simulación y circuito específicos.",
   "gridPos": { "x": 0, "y": 0, "h": 13, "w": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  CONCAT(equipo, ' - ', carro) AS category, \n  CAST(tiempo_segundos AS DECIMAL(12,3)) AS tiempo_segundos,\n  CAST(p_total AS INT) AS p_total,\n  CAST(a_total AS INT) AS a_total,\n  CAST(m_total AS INT) AS m_total,\n  circuito,\n  equipo\nFROM dbo.v_grafana_tiempo_vs_pam\nWHERE circuito = ${circuito:sqlstring}\n  AND id_simulacion = $simulation_id\n  AND id_carro = $carro \nORDER BY tiempo_segundos ASC;"
    }
   ]
  }
 ]
}