const { getPool } = require('../config/database');
const sql = require('mssql');
const logger = require('../config/logger');

const protect = async (req, res, next) => {
  try {
    const sessionId = req.cookies?.sessionId;
    // Only accept identifiers generated by the login service.
    if (typeof sessionId !== 'string' || !/^[a-f0-9]{64}$/.test(sessionId)) {
      return res.status(401).json({ error: 'Sesión inválida o expirada' });
    }
    const result = await getPool().request()
      .input('sessionId', sql.VarChar(64), sessionId)
      .query(`
        SELECT s.id_usuario, u.nombre, u.rol, u.id_equipo
        FROM dbo.sesion s
        JOIN dbo.usuario u ON s.id_usuario = u.id_usuario
        WHERE s.id_sesion = @sessionId AND s.expira > SYSUTCDATETIME()
          AND u.activo = 1
      `);
    const user = result.recordset[0];
    if (!user || !['Admin', 'Engineer', 'Driver'].includes(user.rol)) {
      return res.status(401).json({ error: 'Sesión inválida o expirada' });
    }
    req.user = user;
    return next();
  } catch (error) {
    logger.error('Session lookup failed');
    return res.status(500).json({ error: 'Error interno del servidor' });
  }
};

const requireRole = (...roles) => (req, res, next) => {
  if (!req.user) return res.status(401).json({ error: 'Sesión requerida' });
  if (!roles.includes(req.user.rol)) return res.status(403).json({ error: 'No autorizado' });
  return next();
};

module.exports = { protect, requireRole };
